### ISSUE TITLE
"acceptValue.includes is not a function" build error

### ISSUE THREAD

**Issue by seanw** [notoriousb1t/vuejs-typestyle-seed#1]
After running "npm i" and "npm start" I get this error:

```
Module build failed: TypeError: home/vuejs-typestyle-seed/src/components/entry.tsx: acceptValue.includes is not a function
    at module.exports (home/vuejs-typestyle-seed/node_modules/babel-plugin-transform-vue-jsx/lib/must-use-prop.js:4:38)
    at home/vuejs-typestyle-seed/node_modules/babel-plugin-transform-vue-jsx/index.js:84:19
    at Array.forEach (native)
    at JSXOpeningElement (home/vuejs-typestyle-seed/node_modules/babel-plugin-transform-vue-jsx/index.js:75:24)
    at NodePath._call (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
    at NodePath.visit (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:115:19)
    at TraversalContext.visitQueue (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (home/vuejs-typestyle-seed/node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
 @ ./src/components/index.ts 19:13-31
 @ ./src/main.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./main.tsx
```

I can build the project if I remove this from entry.tsx:

`<input class={this.inputClass} value={this.message} onInput={this.onInputChanged} autofocus />
`
Or if I remove this from babel-plugin-transform-vue-jsx/lib/must-use-prop.js:

`    (attr === 'value' && acceptValue.includes(tag)) && type !== 'button' ||`

What would be a better fix for this? 

Thanks for the starter pack!

**Comment by notoriousb1t** [comment]
What version of node and architecture are you using?  I am not seeing this error, and it looks like it stems from Array.prototype.includes not being present.  That makes me think that either babel doesn't think it exists or the node version is too old to have implemented it.

**Comment by seanw** [comment]
Yes, you're right. I thought I was running the latest stable but I wasn't.
